const encoder=new TextEncoder();
function pdfEsc(value=''){return String(value).replace(/\\/g,'\\\\').replace(/\(/g,'\\(').replace(/\)/g,'\\)').replace(/[\r\n]+/g,' ');}
function ascii(value=''){return String(value).normalize('NFKD').replace(/[^\x20-\x7E]/g,'?');}
function fmtMoney(amount,currency){const n=Number(amount||0);return `${currency} ${n.toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})}`;}
function linesForReport(state,snapshot,{personName=''}={}){
  const lines=[];
  lines.push({text:personName?`Statement - ${personName}`:'Money Tracker Report',size:20,bold:true,gap:9});
  lines.push({text:state?.settings?.displayName||'My Ledger',size:11,gap:12});
  if(snapshot.filters.from||snapshot.filters.to)lines.push({text:`Period: ${snapshot.filters.from||'Beginning'} to ${snapshot.filters.to||'Today'}`,size:10,gap:12});
  lines.push({text:`Transactions in period: ${snapshot.transactionCount}`,size:11,bold:true,gap:8});
  for(const [currency,v] of Object.entries(snapshot.activity))lines.push({text:`${currency}: charged ${fmtMoney(v.charged,currency)}, recovered ${fmtMoney(v.recovered,currency)}, borrowed ${fmtMoney(v.borrowed,currency)}, repaid ${fmtMoney(v.repaid,currency)}`,size:9,gap:6});
  lines.push({text:'Outstanding balances',size:13,bold:true,gap:8});
  const outstanding=personName?snapshot.outstanding.filter(r=>r.personName===personName):snapshot.outstanding;
  if(!outstanding.length)lines.push({text:'No outstanding balances.',size:10,gap:6});
  for(const row of outstanding.slice(0,30))lines.push({text:`${row.personName}: ${row.direction==='owes_me'?'owes you':'you owe'} ${fmtMoney(Math.abs(row.amount),row.currency)}`,size:10,gap:6});
  if(!personName){
    lines.push({text:'Accounts',size:13,bold:true,gap:8});
    for(const a of snapshot.accounts.slice(0,20))lines.push({text:`${a.name} (${a.type}) - ${fmtMoney(a.balance,a.currency)}`,size:10,gap:6});
    if(snapshot.merchants.length){lines.push({text:'Top merchants / sources',size:13,bold:true,gap:8});for(const m of snapshot.merchants.slice(0,10))lines.push({text:`${m.merchant}: ${fmtMoney(m.amount,m.currency)} across ${m.count} transaction${m.count===1?'':'s'}`,size:10,gap:6});}
  }
  lines.push({text:'Generated by Money Tracker',size:8,gap:0});
  return lines;
}
function pageContent(lines,pageNo,pageCount){
  let y=792;const out=['q','0.96 0.97 0.99 rg','36 760 540 54 re f','Q'];
  for(const line of lines){
    y-=line.gap??6; const font=line.bold?'F2':'F1';
    out.push(`BT /${font} ${line.size||10} Tf 0.12 0.15 0.2 rg 48 ${y} Td (${pdfEsc(ascii(line.text))}) Tj ET`);
    y-=line.size||10;
  }
  out.push(`BT /F1 8 Tf 0.45 0.48 0.52 rg 48 28 Td (Page ${pageNo} of ${pageCount}) Tj ET`);
  return out.join('\n');
}
export function buildPdfReport(state,snapshot,options={}){
  const all=linesForReport(state,snapshot,options), pages=[]; let current=[], used=0;
  for(const line of all){const h=(line.size||10)+(line.gap??6);if(current.length&&used+h>690){pages.push(current);current=[];used=0;}current.push(line);used+=h;}if(current.length||!pages.length)pages.push(current);
  const objects=[null];
  objects[1]='<< /Type /Catalog /Pages 2 0 R >>';
  const pageIds=[], contentIds=[]; let next=5;
  for(let i=0;i<pages.length;i++){pageIds.push(next++);contentIds.push(next++);}
  objects[2]=`<< /Type /Pages /Kids [${pageIds.map(id=>`${id} 0 R`).join(' ')}] /Count ${pages.length} >>`;
  objects[3]='<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>';
  objects[4]='<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>';
  for(let i=0;i<pages.length;i++){
    const content=pageContent(pages[i],i+1,pages.length), contentBytes=encoder.encode(content);
    objects[pageIds[i]]=`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 3 0 R /F2 4 0 R >> >> /Contents ${contentIds[i]} 0 R >>`;
    objects[contentIds[i]]=`<< /Length ${contentBytes.length} >>\nstream\n${content}\nendstream`;
  }
  let pdf='%PDF-1.4\n%MoneyTracker\n', offsets=[0];
  for(let i=1;i<objects.length;i++){offsets[i]=encoder.encode(pdf).length;pdf+=`${i} 0 obj\n${objects[i]}\nendobj\n`;}
  const xref=encoder.encode(pdf).length;pdf+=`xref\n0 ${objects.length}\n0000000000 65535 f \n`;for(let i=1;i<objects.length;i++)pdf+=`${String(offsets[i]).padStart(10,'0')} 00000 n \n`;
  pdf+=`trailer\n<< /Size ${objects.length} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;
  return encoder.encode(pdf);
}
